// NIST 800-53 Rev 5 Control Descriptions Database
// Format: { controlId: { title, description, implementation, relatedASI } }

export const NIST_CONTROL_DESCRIPTIONS: Record<string, {
  title: string;
  description: string;
  implementation: string;
  relatedASI: string[];
}> = {
  // AC — Access Control
  "AC-1": {
    title: "Access Control Policy & Procedures",
    description: "Establishes and documents access control policies and procedures that govern how access to information systems and data is managed, enforced, and reviewed.",
    implementation: "Organizations develop and maintain access control policies that address assignment of access rights, revocation of access, periodic review, and enforcement of least privilege principles. For agentic AI systems, policies must address agent tool access, goal-modification authority, and delegation boundaries.",
    relatedASI: ["ASI01", "ASI03"],
  },
  "AC-2": {
    title: "Account Management",
    description: "Manages information system accounts, including creation, enabling, disabling, and removal of accounts.",
    implementation: "Organizations establish procedures for account lifecycle management. For agentic AI systems, this includes managing service accounts for agents, enforcing account naming conventions, and implementing account review processes to detect unauthorized or orphaned agent accounts.",
    relatedASI: ["ASI01", "ASI03"],
  },
  "AC-3": {
    title: "Access Enforcement",
    description: "Enforces approved authorizations for logical access to information and system resources in accordance with applicable access control policies.",
    implementation: "Organizations define and enforce access control mechanisms that prevent unauthorized access to system resources. For agentic AI systems, this includes restricting agent tool access and goal-modification capabilities to authorized principals only, implementing capability-based security models, and enforcing least privilege for agent execution contexts.",
    relatedASI: ["ASI01", "ASI03"],
  },
  "AC-4": {
    title: "Information Flow Enforcement",
    description: "Enforces approved information flows between system components and external systems based on information flow policies.",
    implementation: "Organizations implement mechanisms to control information flow (data, control signals, metadata) within and between systems. For agentic AI systems, this includes enforcing boundaries on tool output consumption, preventing agents from accessing unauthorized data sources, and implementing data classification controls.",
    relatedASI: ["ASI01", "ASI02"],
  },
  "AC-5": {
    title: "Separation of Duties",
    description: "Separates duties and responsibilities to reduce the risk of error and fraud by ensuring no single individual can perform critical functions.",
    implementation: "Organizations implement role-based access controls and segregate incompatible duties. For agentic AI systems, this includes separating agent execution roles from agent configuration/deployment roles, preventing agents from modifying their own prompts or permissions, and requiring multi-party approval for sensitive operations.",
    relatedASI: ["ASI03"],
  },
  "AC-6": {
    title: "Least Privilege",
    description: "Restricts access to information and system resources to the minimum necessary to accomplish assigned functions.",
    implementation: "Organizations grant users and processes only the minimum permissions required for their assigned tasks. For agentic AI systems, this includes limiting agent tool access to only necessary functions, restricting agent execution context permissions, and implementing time-bound or task-bound privilege elevation.",
    relatedASI: ["ASI01", "ASI03"],
  },
  "AC-7": {
    title: "Unsuccessful Login Attempts",
    description: "Enforces a limit on unsuccessful login attempts and implements account lockout or other mechanisms to prevent unauthorized access.",
    implementation: "Organizations configure systems to enforce login attempt limits and implement account lockout policies. For agentic AI systems, this includes rate-limiting agent authentication attempts and monitoring for brute-force attacks against agent credentials or API keys.",
    relatedASI: ["ASI03"],
  },
  "AC-8": {
    title: "System Use Notification",
    description: "Displays authorized use notification messages to users before granting access to the system.",
    implementation: "Organizations implement system banners and notification messages that inform users of authorized use policies and monitoring. For agentic AI systems, this includes displaying warnings to users about agent capabilities, limitations, and monitoring of agent actions.",
    relatedASI: [],
  },
  "AC-9": {
    title: "Previous Login Notification",
    description: "Notifies users of the date and time of their last successful login and any unsuccessful login attempts since the last successful login.",
    implementation: "Organizations configure systems to display previous login information to users upon authentication. For agentic AI systems, this includes logging and reporting agent authentication events to enable detection of unauthorized agent access.",
    relatedASI: ["ASI03"],
  },
  "AC-10": {
    title: "Concurrent Session Control",
    description: "Limits the number of concurrent sessions for each user account to prevent unauthorized access through session hijacking or replay attacks.",
    implementation: "Organizations enforce concurrent session limits and implement session management controls. For agentic AI systems, this includes limiting concurrent agent instances, preventing session reuse, and implementing session timeout mechanisms.",
    relatedASI: ["ASI03"],
  },

  // AU — Audit & Accountability
  "AU-1": {
    title: "Audit & Accountability Policy & Procedures",
    description: "Establishes and documents audit and accountability policies and procedures for logging, monitoring, and reviewing system activities.",
    implementation: "Organizations develop comprehensive audit policies that define logging requirements, retention periods, and review procedures. For agentic AI systems, policies must address logging of agent actions, goal changes, tool invocations, and behavioral anomalies.",
    relatedASI: ["ASI01", "ASI08"],
  },
  "AU-2": {
    title: "Audit Events",
    description: "Defines the types of system events that should be logged and establishes criteria for logging those events.",
    implementation: "Organizations identify and document auditable events including authentication, authorization, configuration changes, and security-relevant actions. For agentic AI systems, auditable events include agent initialization, goal modifications, tool access, permission changes, and anomalous behavior patterns.",
    relatedASI: ["ASI01", "ASI08"],
  },
  "AU-3": {
    title: "Content of Audit Records",
    description: "Ensures that audit records contain sufficient information to establish what events occurred, who caused them, when they occurred, and their outcomes.",
    implementation: "Organizations configure audit logging to capture user/process identity, timestamps, event type, resource accessed, and outcome. For agentic AI systems, audit records must include agent identity, action type, affected resources, tool invocations, and behavioral context.",
    relatedASI: ["ASI01", "ASI08"],
  },
  "AU-4": {
    title: "Audit Storage Capacity",
    description: "Allocates sufficient storage capacity for audit records and implements mechanisms to handle audit storage capacity issues.",
    implementation: "Organizations provision adequate storage for audit logs and implement log rotation, archival, and retention policies. For agentic AI systems, this includes capacity planning for high-volume agent action logs and implementing efficient log compression/archival.",
    relatedASI: [],
  },
  "AU-5": {
    title: "Response to Audit Processing Failures",
    description: "Alerts system administrators when audit processing fails and implements procedures to address audit processing failures.",
    implementation: "Organizations configure alerts for audit system failures and implement procedures to address logging gaps. For agentic AI systems, this includes monitoring agent audit log integrity and alerting when agent action logging is unavailable.",
    relatedASI: ["ASI08"],
  },
  "AU-6": {
    title: "Audit Record Review, Analysis & Reporting",
    description: "Reviews, analyzes, and reports on audit records to identify security-relevant events and anomalies.",
    implementation: "Organizations establish procedures for regular audit log review, analysis of security events, and reporting of findings. For agentic AI systems, this includes analyzing agent behavior patterns, detecting goal drift, identifying unauthorized tool usage, and reporting anomalies.",
    relatedASI: ["ASI01", "ASI08"],
  },
  "AU-7": {
    title: "Audit Reduction & Report Generation",
    description: "Provides mechanisms to reduce audit data volume and generate audit reports for analysis.",
    implementation: "Organizations implement audit log filtering, correlation, and reporting tools to manage large volumes of audit data. For agentic AI systems, this includes tools to correlate agent actions across multiple systems and generate reports on agent behavior patterns.",
    relatedASI: [],
  },
  "AU-8": {
    title: "Time Stamps",
    description: "Uses accurate time stamps in audit records to enable correlation of events across systems.",
    implementation: "Organizations synchronize system clocks using NTP or similar mechanisms and record precise timestamps in audit logs. For agentic AI systems, accurate timestamps enable correlation of agent actions across distributed systems and detection of timing-based attacks.",
    relatedASI: ["ASI08"],
  },
  "AU-9": {
    title: "Protection of Audit Information",
    description: "Protects audit records and audit tools from unauthorized access, modification, and deletion.",
    implementation: "Organizations implement access controls, encryption, and integrity verification for audit logs. For agentic AI systems, this includes protecting agent action logs from tampering and ensuring audit log integrity through cryptographic hashing or digital signatures.",
    relatedASI: ["ASI01", "ASI08"],
  },
  "AU-10": {
    title: "Non-Repudiation",
    description: "Provides mechanisms to prevent individuals from denying that they performed specific actions.",
    implementation: "Organizations implement digital signatures, cryptographic hashing, and other mechanisms to provide non-repudiation. For agentic AI systems, this includes cryptographically signing agent actions to prevent agents from denying their actions.",
    relatedASI: ["ASI01"],
  },
  "AU-11": {
    title: "Audit Record Retention",
    description: "Retains audit records for a defined period to support after-the-fact investigation of security incidents.",
    implementation: "Organizations establish audit log retention policies based on regulatory requirements and organizational risk. For agentic AI systems, retention periods should accommodate investigation of agent-related incidents and anomalies.",
    relatedASI: [],
  },
  "AU-12": {
    title: "Audit Record Generation",
    description: "Provides mechanisms to generate audit records for system events and user actions.",
    implementation: "Organizations configure systems to automatically generate audit records for security-relevant events. For agentic AI systems, this includes automatic logging of agent initialization, goal changes, tool invocations, permission modifications, and behavioral anomalies.",
    relatedASI: ["ASI01", "ASI08"],
  },

  // CA — Assessment & Authorization
  "CA-1": {
    title: "Security Assessment & Authorization Policy & Procedures",
    description: "Establishes and documents policies and procedures for conducting security assessments and authorizing systems for operation.",
    implementation: "Organizations develop assessment and authorization policies that define assessment scope, frequency, and authorization criteria. For agentic AI systems, policies must address assessment of agent security controls, goal alignment verification, and authorization of agent deployment.",
    relatedASI: [],
  },
  "CA-2": {
    title: "Security Assessments",
    description: "Conducts security assessments of systems to determine the effectiveness of security controls.",
    implementation: "Organizations perform periodic security assessments using established methodologies and tools. For agentic AI systems, assessments should evaluate agent goal alignment, tool access restrictions, behavioral monitoring, and incident response capabilities.",
    relatedASI: [],
  },
  "CA-3": {
    title: "System Interconnections",
    description: "Authorizes, monitors, and controls connections between systems and external networks.",
    implementation: "Organizations establish procedures for authorizing system interconnections and implementing security controls for data exchange. For agentic AI systems, this includes controlling agent-to-agent communication, agent-to-external-service connections, and implementing data validation for inter-agent communication.",
    relatedASI: ["ASI07"],
  },
  "CA-5": {
    title: "Plan of Action & Milestones",
    description: "Develops and maintains a plan to address security control deficiencies identified during assessments.",
    implementation: "Organizations document security findings and develop remediation plans with target completion dates. For agentic AI systems, this includes addressing control gaps related to agent security, goal alignment, and behavioral monitoring.",
    relatedASI: [],
  },
  "CA-6": {
    title: "Security Authorization",
    description: "Obtains authorization to operate a system based on assessment results and management acceptance of risk.",
    implementation: "Organizations establish authorization procedures and obtain management approval for system operation. For agentic AI systems, authorization should be contingent on successful security assessment and demonstration of goal alignment controls.",
    relatedASI: [],
  },
  "CA-7": {
    title: "Continuous Monitoring",
    description: "Implements continuous monitoring of security controls to maintain current knowledge of system security posture.",
    implementation: "Organizations establish continuous monitoring programs that track security control effectiveness over time. For agentic AI systems, continuous monitoring should track agent behavior, goal alignment, tool usage patterns, and anomaly detection.",
    relatedASI: ["ASI01", "ASI08"],
  },
  "CA-8": {
    title: "Penetration Testing",
    description: "Conducts penetration testing to identify vulnerabilities and test the effectiveness of security controls.",
    implementation: "Organizations perform periodic penetration testing using authorized security professionals. For agentic AI systems, penetration testing should attempt to trigger goal hijack, unauthorized tool usage, and other agentic AI-specific vulnerabilities.",
    relatedASI: ["ASI01", "ASI02", "ASI05"],
  },
  "CA-9": {
    title: "Internal System Connections",
    description: "Authorizes and monitors internal connections between system components.",
    implementation: "Organizations establish procedures for authorizing internal system connections and implementing security controls. For agentic AI systems, this includes controlling communication between agent components and implementing message validation.",
    relatedASI: ["ASI07"],
  },

  // CM — Configuration Management
  "CM-1": {
    title: "Configuration Management Policy & Procedures",
    description: "Establishes and documents configuration management policies and procedures for maintaining system baseline configurations.",
    implementation: "Organizations develop configuration management policies that define baseline configuration requirements, change control procedures, and configuration verification. For agentic AI systems, policies must address agent configuration management, prompt versioning, and tool access configuration.",
    relatedASI: ["ASI01"],
  },
  "CM-2": {
    title: "Baseline Configuration",
    description: "Establishes and maintains a baseline configuration for systems that reflects the current approved configuration.",
    implementation: "Organizations document baseline configurations including hardware, software, and security settings. For agentic AI systems, baseline configurations should include agent system prompts, tool access lists, permission settings, and behavioral parameters.",
    relatedASI: ["ASI01"],
  },
  "CM-3": {
    title: "Configuration Change Control",
    description: "Implements procedures to control changes to system configurations and ensures changes are reviewed and approved before implementation.",
    implementation: "Organizations establish change control procedures including change requests, review, approval, testing, and implementation. For agentic AI systems, this includes controlling changes to agent prompts, tool access, permissions, and behavioral parameters with multi-party approval for sensitive changes.",
    relatedASI: ["ASI01"],
  },
  "CM-4": {
    title: "Security Impact Analysis",
    description: "Analyzes the security impact of proposed configuration changes before implementation.",
    implementation: "Organizations conduct security impact analysis for all proposed changes. For agentic AI systems, impact analysis should assess how configuration changes affect goal alignment, tool access restrictions, and behavioral controls.",
    relatedASI: ["ASI01"],
  },
  "CM-5": {
    title: "Access Restrictions for Change",
    description: "Restricts access to configuration change procedures and implements approval requirements for configuration changes.",
    implementation: "Organizations limit configuration change authority to authorized personnel and require approval from multiple parties for sensitive changes. For agentic AI systems, this includes restricting agent prompt modification to authorized personnel and requiring approval for changes to agent permissions.",
    relatedASI: ["ASI01", "ASI03"],
  },
  "CM-6": {
    title: "Configuration Settings",
    description: "Establishes and documents mandatory configuration settings for systems and implements mechanisms to enforce those settings.",
    implementation: "Organizations define required security configuration settings and implement automated enforcement mechanisms. For agentic AI systems, this includes enforcing required agent configuration settings such as goal alignment verification, tool access restrictions, and behavioral monitoring.",
    relatedASI: ["ASI01"],
  },
  "CM-7": {
    title: "Least Functionality",
    description: "Configures systems to provide only essential capabilities and disables unnecessary functions and services.",
    implementation: "Organizations disable unnecessary system services, ports, and protocols. For agentic AI systems, this includes disabling unnecessary agent capabilities, restricting tool access to only required functions, and minimizing agent execution context permissions.",
    relatedASI: ["ASI01", "ASI02"],
  },
  "CM-8": {
    title: "Information System Component Inventory",
    description: "Develops, maintains, and reviews an inventory of system components including hardware, software, and firmware.",
    implementation: "Organizations maintain detailed inventories of system components and track component versions and patches. For agentic AI systems, this includes inventorying deployed agents, agent versions, tool integrations, and model versions.",
    relatedASI: [],
  },
  "CM-9": {
    title: "Configuration Management Plan",
    description: "Develops and documents a configuration management plan that describes the organization's approach to configuration management.",
    implementation: "Organizations document their configuration management approach including roles, responsibilities, procedures, and tools. For agentic AI systems, the plan should address agent configuration management, prompt versioning, and tool access management.",
    relatedASI: [],
  },
  "CM-10": {
    title: "Software Use Restrictions",
    description: "Implements restrictions on software use to prevent unauthorized installation and use of software.",
    implementation: "Organizations establish software use policies and implement mechanisms to enforce software restrictions. For agentic AI systems, this includes restricting agent tool integrations to approved tools and preventing agents from installing or executing unauthorized code.",
    relatedASI: ["ASI02", "ASI05"],
  },
  "CM-11": {
    title: "User-Installed Software",
    description: "Establishes procedures to prevent unauthorized installation of software by users.",
    implementation: "Organizations implement technical controls to prevent unauthorized software installation. For agentic AI systems, this includes preventing agents from installing unauthorized tools or modifying their own execution environment.",
    relatedASI: ["ASI02", "ASI05"],
  },

  // CP — Contingency Planning
  "CP-1": {
    title: "Contingency Planning Policy & Procedures",
    description: "Establishes and documents contingency planning policies and procedures for responding to system disruptions.",
    implementation: "Organizations develop contingency planning policies that define recovery objectives, procedures, and responsibilities. For agentic AI systems, policies must address agent failure scenarios, goal state recovery, and behavioral anomaly response.",
    relatedASI: ["ASI08"],
  },
  "CP-2": {
    title: "Contingency Plan",
    description: "Develops and maintains a contingency plan that describes procedures for responding to system disruptions and recovering system functionality.",
    implementation: "Organizations develop detailed contingency plans including recovery procedures, resource requirements, and testing schedules. For agentic AI systems, plans should address agent failure recovery, goal state restoration, and cascading failure prevention.",
    relatedASI: ["ASI08"],
  },
  "CP-3": {
    title: "Contingency Training",
    description: "Provides training to personnel on contingency plan procedures and their roles in responding to system disruptions.",
    implementation: "Organizations conduct contingency training for personnel responsible for incident response and system recovery. For agentic AI systems, training should address agent failure scenarios and recovery procedures.",
    relatedASI: [],
  },
  "CP-4": {
    title: "Contingency Plan Testing & Exercises",
    description: "Tests and exercises the contingency plan to ensure its effectiveness and personnel familiarity with procedures.",
    implementation: "Organizations conduct periodic contingency plan tests and exercises to validate procedures and identify gaps. For agentic AI systems, testing should include agent failure scenarios and goal state recovery procedures.",
    relatedASI: ["ASI08"],
  },
  "CP-5": {
    title: "Contingency Plan Update",
    description: "Updates the contingency plan to reflect changes in system architecture, procedures, or organizational requirements.",
    implementation: "Organizations review and update contingency plans periodically or when significant system changes occur. For agentic AI systems, updates should reflect changes to agent architecture, tool integrations, or behavioral controls.",
    relatedASI: [],
  },
  "CP-6": {
    title: "Alternate Processing Site",
    description: "Establishes an alternate processing site to enable system recovery and continued operation in case of primary site failure.",
    implementation: "Organizations establish backup processing facilities with necessary resources and data to enable rapid recovery. For agentic AI systems, this includes backup agent deployment sites and recovery of agent state/memory.",
    relatedASI: ["ASI08"],
  },
  "CP-7": {
    title: "Alternate Storage Site",
    description: "Establishes an alternate storage site to protect critical data and enable data recovery in case of primary storage failure.",
    implementation: "Organizations implement off-site data backup and storage to enable data recovery. For agentic AI systems, this includes backing up agent configurations, learned models, and interaction history.",
    relatedASI: ["ASI08"],
  },
  "CP-8": {
    title: "Telecommunications Services",
    description: "Establishes alternate telecommunications services to enable continued system operation in case of primary service failure.",
    implementation: "Organizations establish backup telecommunications services and connectivity options. For agentic AI systems, this includes backup communication channels for agent-to-system communication.",
    relatedASI: ["ASI08"],
  },
  "CP-9": {
    title: "Information System Backup",
    description: "Conducts, tests, and maintains backups of critical information system components and data.",
    implementation: "Organizations implement regular backup procedures, test backup restoration, and maintain backup media. For agentic AI systems, backups should include agent configurations, learned models, and interaction logs.",
    relatedASI: ["ASI08"],
  },
  "CP-10": {
    title: "Information System Recovery & Reconstitution",
    description: "Provides mechanisms to recover and reconstitute systems to a known secure state after a disruption or compromise.",
    implementation: "Organizations establish procedures to restore systems to a known secure state including configuration verification and integrity checking. For agentic AI systems, recovery should include verification of agent goal alignment and behavioral controls.",
    relatedASI: ["ASI08"],
  },
  "CP-11": {
    title: "Alternate Communications Protocols",
    description: "Establishes alternate communications protocols to enable continued system operation in case of primary protocol failure.",
    implementation: "Organizations implement support for alternate communications protocols and formats. For agentic AI systems, this includes support for alternate agent communication protocols.",
    relatedASI: [],
  },
  "CP-12": {
    title: "Safe Mode & Recovery",
    description: "Provides mechanisms to operate systems in a safe mode with reduced functionality during recovery procedures.",
    implementation: "Organizations implement safe mode capabilities that enable system operation with essential functions only. For agentic AI systems, safe mode should disable non-essential agent capabilities and enable manual oversight.",
    relatedASI: ["ASI08"],
  },
  "CP-13": {
    title: "Alternate Processing & Recovery Time",
    description: "Defines and implements recovery time objectives and recovery point objectives for critical systems.",
    implementation: "Organizations establish and document recovery time objectives (RTO) and recovery point objectives (RPO) for critical systems. For agentic AI systems, RTO/RPO should reflect the criticality of agent services.",
    relatedASI: [],
  },

  // IA — Identification & Authentication
  "IA-1": {
    title: "Identification & Authentication Policy & Procedures",
    description: "Establishes and documents identification and authentication policies and procedures for verifying user and system identities.",
    implementation: "Organizations develop identification and authentication policies that define authentication requirements, mechanisms, and verification procedures. For agentic AI systems, policies must address agent authentication, service account management, and multi-factor authentication.",
    relatedASI: ["ASI03"],
  },
  "IA-2": {
    title: "Authentication",
    description: "Implements authentication mechanisms to verify the identity of users and systems before granting access.",
    implementation: "Organizations implement authentication mechanisms including passwords, multi-factor authentication, and cryptographic credentials. For agentic AI systems, this includes authenticating agents to systems, verifying agent identity before tool access, and implementing service account authentication.",
    relatedASI: ["ASI03"],
  },
  "IA-3": {
    title: "Device Identification & Authentication",
    description: "Implements mechanisms to identify and authenticate devices before granting access to systems.",
    implementation: "Organizations implement device identification and authentication mechanisms such as certificates or hardware tokens. For agentic AI systems, this includes identifying and authenticating agent execution environments.",
    relatedASI: ["ASI03"],
  },
  "IA-4": {
    title: "Identifier Management",
    description: "Manages user and system identifiers to ensure unique identification and prevent identifier reuse.",
    implementation: "Organizations establish procedures for creating, maintaining, and retiring identifiers. For agentic AI systems, this includes managing agent identifiers, service account names, and preventing identifier reuse.",
    relatedASI: ["ASI03"],
  },
  "IA-5": {
    title: "Authentication Mechanisms",
    description: "Implements authentication mechanisms that meet organizational requirements for strength and security.",
    implementation: "Organizations select and implement appropriate authentication mechanisms based on security requirements. For agentic AI systems, this includes implementing strong authentication for agent access to sensitive functions.",
    relatedASI: ["ASI03"],
  },
  "IA-6": {
    title: "Access to Authentication Information",
    description: "Protects authentication information (passwords, cryptographic keys) from unauthorized access and disclosure.",
    implementation: "Organizations implement controls to protect authentication credentials including encryption, access restrictions, and secure storage. For agentic AI systems, this includes protecting agent credentials and API keys from unauthorized access.",
    relatedASI: ["ASI03"],
  },
  "IA-7": {
    title: "Cryptographic Module Authentication",
    description: "Implements cryptographic authentication mechanisms that meet FIPS standards.",
    implementation: "Organizations use FIPS-approved cryptographic modules for authentication. For agentic AI systems, this includes using approved cryptographic mechanisms for agent authentication and credential protection.",
    relatedASI: [],
  },
  "IA-8": {
    title: "Identification & Authentication for Non-Organizational Users",
    description: "Implements identification and authentication mechanisms for users from external organizations.",
    implementation: "Organizations establish procedures for authenticating external users and implementing appropriate access controls. For agentic AI systems, this includes authenticating agents from external systems and implementing appropriate access restrictions.",
    relatedASI: ["ASI03"],
  },
  "IA-9": {
    title: "Service Identification & Authentication",
    description: "Implements mechanisms to identify and authenticate services before granting access.",
    implementation: "Organizations implement service authentication mechanisms such as certificates or API keys. For agentic AI systems, this includes authenticating agent services and implementing service-to-service authentication.",
    relatedASI: ["ASI03"],
  },
  "IA-10": {
    title: "Adaptive Authentication",
    description: "Implements adaptive authentication mechanisms that adjust authentication requirements based on risk assessment.",
    implementation: "Organizations implement risk-based authentication that increases authentication requirements for higher-risk scenarios. For agentic AI systems, this includes implementing adaptive authentication based on agent behavior anomalies.",
    relatedASI: ["ASI03"],
  },
  "IA-11": {
    title: "Re-authentication",
    description: "Requires re-authentication for sensitive operations to ensure continued authorization.",
    implementation: "Organizations implement re-authentication requirements for sensitive operations. For agentic AI systems, this includes requiring re-authentication for sensitive agent operations such as goal modification.",
    relatedASI: ["ASI03"],
  },
  "IA-12": {
    title: "Cryptographic Key Establishment & Management",
    description: "Manages cryptographic keys used for authentication and implements secure key establishment procedures.",
    implementation: "Organizations establish procedures for generating, storing, protecting, and retiring cryptographic keys. For agentic AI systems, this includes managing cryptographic keys used for agent authentication.",
    relatedASI: [],
  },

  // IR — Incident Response
  "IR-1": {
    title: "Incident Response Policy & Procedures",
    description: "Establishes and documents incident response policies and procedures for detecting, responding to, and recovering from security incidents.",
    implementation: "Organizations develop incident response policies that define incident categories, response procedures, and communication protocols. For agentic AI systems, policies must address agent-related incidents including goal hijack, unauthorized tool usage, and cascading failures.",
    relatedASI: ["ASI08"],
  },
  "IR-2": {
    title: "Incident Response Training",
    description: "Provides training to personnel on incident response procedures and their roles in responding to security incidents.",
    implementation: "Organizations conduct incident response training for personnel responsible for incident detection and response. For agentic AI systems, training should address agent-related incident scenarios and response procedures.",
    relatedASI: [],
  },
  "IR-3": {
    title: "Incident Response Testing",
    description: "Tests incident response procedures to ensure their effectiveness and personnel familiarity with procedures.",
    implementation: "Organizations conduct periodic incident response exercises and simulations. For agentic AI systems, testing should include agent-related incident scenarios.",
    relatedASI: [],
  },
  "IR-4": {
    title: "Incident Handling",
    description: "Implements procedures to handle security incidents including detection, analysis, containment, and recovery.",
    implementation: "Organizations establish incident handling procedures including triage, analysis, containment, and recovery. For agentic AI systems, procedures should address agent-related incidents and include agent isolation/shutdown capabilities.",
    relatedASI: ["ASI08"],
  },
  "IR-5": {
    title: "Incident Monitoring",
    description: "Monitors and tracks security incidents to ensure appropriate response and resolution.",
    implementation: "Organizations implement incident tracking and monitoring to ensure incidents are properly handled and resolved. For agentic AI systems, this includes tracking agent-related incidents and monitoring remediation progress.",
    relatedASI: [],
  },
  "IR-6": {
    title: "Incident Reporting",
    description: "Reports security incidents to appropriate internal and external parties.",
    implementation: "Organizations establish procedures for reporting security incidents to management, law enforcement, and regulatory agencies as required. For agentic AI systems, this includes reporting agent-related incidents.",
    relatedASI: [],
  },
  "IR-7": {
    title: "Incident Response Assistance",
    description: "Provides assistance to other organizations in responding to security incidents.",
    implementation: "Organizations establish procedures for providing incident response assistance to other organizations. For agentic AI systems, this includes sharing information about agent-related incident response.",
    relatedASI: [],
  },
  "IR-8": {
    title: "Incident Response Plan",
    description: "Develops and maintains an incident response plan that describes procedures for responding to security incidents.",
    implementation: "Organizations develop detailed incident response plans including roles, responsibilities, communication procedures, and recovery steps. For agentic AI systems, plans should address agent-related incidents and include agent shutdown/recovery procedures.",
    relatedASI: ["ASI08"],
  },
  "IR-9": {
    title: "Information Spillage Response",
    description: "Implements procedures to respond to information spillage incidents where sensitive information is disclosed.",
    implementation: "Organizations establish procedures for responding to information spillage including containment, notification, and remediation. For agentic AI systems, this includes responding to incidents where agents disclose sensitive information.",
    relatedASI: ["ASI06"],
  },
  "IR-10": {
    title: "Integrated Information Security Operations Center",
    description: "Establishes an integrated security operations center for monitoring and responding to security incidents.",
    implementation: "Organizations establish security operations centers with tools and procedures for monitoring and responding to security incidents. For agentic AI systems, SOCs should include monitoring of agent behavior and incident response capabilities.",
    relatedASI: [],
  },

  // MP — Media Protection
  "MP-1": {
    title: "Media Protection Policy & Procedures",
    description: "Establishes and documents media protection policies and procedures for protecting physical and digital media.",
    implementation: "Organizations develop media protection policies that define handling, storage, and destruction procedures. For agentic AI systems, policies must address protection of agent configurations, learned models, and interaction logs.",
    relatedASI: ["ASI06"],
  },
  "MP-2": {
    title: "Media Access",
    description: "Restricts access to media containing sensitive information and implements controls to prevent unauthorized access.",
    implementation: "Organizations implement access controls for media containing sensitive information. For agentic AI systems, this includes restricting access to media containing agent configurations and learned models.",
    relatedASI: ["ASI06"],
  },
  "MP-3": {
    title: "Media Marking",
    description: "Marks media containing sensitive information with appropriate classification labels.",
    implementation: "Organizations implement procedures for marking media with classification labels and handling instructions. For agentic AI systems, this includes marking media containing agent configurations and sensitive data.",
    relatedASI: [],
  },
  "MP-4": {
    title: "Media Storage",
    description: "Stores media in secure locations with appropriate environmental controls and access restrictions.",
    implementation: "Organizations implement secure storage facilities for media with environmental controls and access restrictions. For agentic AI systems, this includes secure storage of backup media containing agent configurations and data.",
    relatedASI: ["ASI06"],
  },
  "MP-5": {
    title: "Media Transport",
    description: "Protects media during transport to prevent unauthorized access or damage.",
    implementation: "Organizations implement procedures for secure transport of media including encryption and physical security. For agentic AI systems, this includes protecting media during transport of agent configurations and backups.",
    relatedASI: ["ASI06"],
  },
  "MP-6": {
    title: "Media Sanitization",
    description: "Sanitizes media before reuse or disposal to prevent recovery of sensitive information.",
    implementation: "Organizations implement media sanitization procedures that render sensitive information unrecoverable. For agentic AI systems, this includes sanitizing media containing agent configurations and interaction logs.",
    relatedASI: ["ASI06"],
  },
  "MP-7": {
    title: "Removable Media Use",
    description: "Restricts use of removable media to prevent unauthorized data transfer.",
    implementation: "Organizations establish policies restricting removable media use and implement technical controls to enforce restrictions. For agentic AI systems, this includes restricting agent access to removable media.",
    relatedASI: ["ASI06"],
  },
  "MP-8": {
    title: "Removable Media Prohibitions",
    description: "Prohibits use of removable media in certain system components or for certain purposes.",
    implementation: "Organizations prohibit removable media use in sensitive system components and implement technical controls to enforce prohibitions. For agentic AI systems, this includes prohibiting removable media use in agent execution environments.",
    relatedASI: ["ASI06"],
  },

  // PE — Physical & Environmental
  "PE-1": {
    title: "Physical & Environmental Protection Policy & Procedures",
    description: "Establishes and documents physical and environmental protection policies and procedures.",
    implementation: "Organizations develop policies for physical security, environmental controls, and facility management. For agentic AI systems, policies must address physical security of agent execution environments and data storage facilities.",
    relatedASI: [],
  },
  "PE-2": {
    title: "Physical Access",
    description: "Restricts physical access to facilities and implements controls to prevent unauthorized entry.",
    implementation: "Organizations implement physical access controls including badges, guards, and surveillance. For agentic AI systems, this includes physical security of data centers hosting agent systems.",
    relatedASI: [],
  },
  "PE-3": {
    title: "Physical Access Monitoring",
    description: "Monitors physical access to facilities and logs access events.",
    implementation: "Organizations implement physical access logging and monitoring systems. For agentic AI systems, this includes monitoring physical access to facilities hosting agent systems.",
    relatedASI: [],
  },
  "PE-4": {
    title: "Access Control for Transmission Medium",
    description: "Controls physical access to transmission media to prevent unauthorized access or damage.",
    implementation: "Organizations implement controls for physical access to network cables, fiber optics, and other transmission media. For agentic AI systems, this includes protecting communication channels used by agents.",
    relatedASI: [],
  },
  "PE-5": {
    title: "Access Control for Output Devices",
    description: "Restricts physical access to output devices and implements controls to prevent unauthorized output.",
    implementation: "Organizations implement controls for output devices including printers and displays. For agentic AI systems, this includes controlling access to output devices used for agent monitoring.",
    relatedASI: [],
  },
  "PE-6": {
    title: "Monitoring Physical Access",
    description: "Monitors physical access to facilities using surveillance systems and access logs.",
    implementation: "Organizations implement surveillance systems and access logging for physical facilities. For agentic AI systems, this includes surveillance of data centers and agent deployment locations.",
    relatedASI: [],
  },
  "PE-8": {
    title: "Visitor Access Records",
    description: "Maintains records of visitor access to facilities.",
    implementation: "Organizations maintain visitor logs and implement visitor escort procedures. For agentic AI systems, this includes logging visitor access to facilities hosting agent systems.",
    relatedASI: [],
  },
  "PE-9": {
    title: "Power Equipment & Cabling",
    description: "Protects power equipment and cabling from damage and unauthorized access.",
    implementation: "Organizations implement physical protection for power equipment and cabling. For agentic AI systems, this includes protecting power infrastructure for agent execution environments.",
    relatedASI: [],
  },
  "PE-10": {
    title: "Emergency Shutoff",
    description: "Provides emergency shutoff capability for power and communications systems.",
    implementation: "Organizations implement emergency shutoff switches for power and communications. For agentic AI systems, this includes emergency shutdown capability for agent systems.",
    relatedASI: ["ASI08"],
  },
  "PE-11": {
    title: "Emergency Power",
    description: "Provides emergency power to enable continued system operation during power outages.",
    implementation: "Organizations implement backup power systems including UPS and generators. For agentic AI systems, this includes backup power for agent execution environments.",
    relatedASI: [],
  },
  "PE-12": {
    title: "Emergency Lighting",
    description: "Provides emergency lighting to enable safe evacuation and continued operations during power outages.",
    implementation: "Organizations implement emergency lighting systems in facilities. For agentic AI systems, this includes emergency lighting in data centers hosting agent systems.",
    relatedASI: [],
  },
  "PE-13": {
    title: "Fire Protection",
    description: "Implements fire detection and suppression systems to protect facilities and equipment.",
    implementation: "Organizations implement fire detection and suppression systems appropriate for the facility. For agentic AI systems, this includes fire protection for data centers hosting agent systems.",
    relatedASI: [],
  },
  "PE-14": {
    title: "Temperature & Humidity",
    description: "Monitors and controls temperature and humidity to maintain appropriate environmental conditions.",
    implementation: "Organizations implement environmental monitoring and control systems. For agentic AI systems, this includes environmental controls for data centers hosting agent systems.",
    relatedASI: [],
  },
  "PE-15": {
    title: "Water Damage Protection",
    description: "Protects facilities and equipment from water damage.",
    implementation: "Organizations implement water damage prevention and detection systems. For agentic AI systems, this includes water damage protection for data centers.",
    relatedASI: [],
  },
  "PE-16": {
    title: "Delivery & Removal",
    description: "Authorizes, monitors, and controls delivery and removal of equipment and supplies.",
    implementation: "Organizations establish procedures for authorizing and monitoring delivery and removal of equipment. For agentic AI systems, this includes controlling delivery of hardware and software for agent systems.",
    relatedASI: [],
  },
  "PE-17": {
    title: "Alternate Work Sites",
    description: "Implements security controls for alternate work sites where employees work remotely.",
    implementation: "Organizations implement security controls for remote work including VPN, encryption, and access controls. For agentic AI systems, this includes securing remote access to agent systems.",
    relatedASI: [],
  },
  "PE-18": {
    title: "Location of Information System Components",
    description: "Plans the location of information system components to minimize potential damage from environmental hazards.",
    implementation: "Organizations plan system component locations to minimize exposure to environmental hazards. For agentic AI systems, this includes locating agent systems away from hazardous areas.",
    relatedASI: [],
  },
  "PE-19": {
    title: "Information Leakage",
    description: "Protects systems from electromagnetic and acoustic information leakage.",
    implementation: "Organizations implement controls to prevent electromagnetic and acoustic information leakage. For agentic AI systems, this includes protecting agent systems from information leakage.",
    relatedASI: ["ASI06"],
  },
  "PE-20": {
    title: "Asset Management",
    description: "Tracks and manages physical assets including hardware and equipment.",
    implementation: "Organizations maintain asset inventories and tracking systems. For agentic AI systems, this includes tracking hardware used for agent systems.",
    relatedASI: [],
  },

  // PL — Planning
  "PL-1": {
    title: "Security Planning Policy & Procedures",
    description: "Establishes and documents security planning policies and procedures.",
    implementation: "Organizations develop security planning policies that define planning requirements and procedures. For agentic AI systems, policies must address security planning for agent systems including threat modeling and control selection.",
    relatedASI: [],
  },
  "PL-2": {
    title: "System Security Plan",
    description: "Develops and maintains a system security plan that describes the system and its security controls.",
    implementation: "Organizations develop comprehensive security plans that document system architecture, threats, and security controls. For agentic AI systems, plans should address agent architecture, threat model, and security controls for agent-related risks.",
    relatedASI: [],
  },
  "PL-4": {
    title: "Rules of Behavior",
    description: "Establishes and documents rules of behavior for system users.",
    implementation: "Organizations establish rules of behavior that define acceptable use of systems and consequences for violations. For agentic AI systems, rules should address appropriate use of agents and restrictions on agent capabilities.",
    relatedASI: [],
  },
  "PL-8": {
    title: "Information Security Architecture",
    description: "Develops an information security architecture that describes how security is integrated into system design.",
    implementation: "Organizations develop security architectures that integrate security throughout system design. For agentic AI systems, architecture should address goal alignment, behavioral monitoring, and incident response.",
    relatedASI: [],
  },

  // PM — Program Management
  "PM-1": {
    title: "Information Security Program Planning",
    description: "Develops and maintains a comprehensive information security program plan.",
    implementation: "Organizations develop security program plans that define security objectives, strategies, and resource requirements. For agentic AI systems, programs should address security of agent systems and agentic AI-specific risks.",
    relatedASI: [],
  },
  "PM-2": {
    title: "Senior Information Security Officer",
    description: "Designates a senior information security officer responsible for information security program.",
    implementation: "Organizations designate a senior security officer with authority and responsibility for security program. For agentic AI systems, security leadership should include expertise in agent security.",
    relatedASI: [],
  },
  "PM-3": {
    title: "Information Security Resources",
    description: "Allocates resources (personnel, budget, tools) to support the information security program.",
    implementation: "Organizations allocate adequate resources to support security program objectives. For agentic AI systems, resources should include personnel with agentic AI security expertise.",
    relatedASI: [],
  },
  "PM-4": {
    title: "Plan of Action & Milestones",
    description: "Develops and maintains a plan to address security control deficiencies.",
    implementation: "Organizations document security findings and develop remediation plans with target completion dates. For agentic AI systems, plans should address control gaps related to agent security.",
    relatedASI: [],
  },
  "PM-5": {
    title: "System Inventory",
    description: "Maintains an inventory of organizational systems.",
    implementation: "Organizations maintain system inventories including system names, owners, and security classifications. For agentic AI systems, inventory should include deployed agents and their security classifications.",
    relatedASI: [],
  },
  "PM-6": {
    title: "Information Security Metrics & Measurement",
    description: "Develops and implements metrics to measure the effectiveness of security controls.",
    implementation: "Organizations establish security metrics and measurement procedures to track control effectiveness. For agentic AI systems, metrics should include agent security posture and incident rates.",
    relatedASI: [],
  },
  "PM-7": {
    title: "Enterprise Architecture",
    description: "Develops an enterprise architecture that integrates security throughout the organization.",
    implementation: "Organizations develop enterprise architectures that integrate security considerations. For agentic AI systems, architecture should address agent deployment and security integration.",
    relatedASI: [],
  },
  "PM-8": {
    title: "Critical Infrastructure Protection",
    description: "Implements security controls for critical infrastructure systems.",
    implementation: "Organizations implement enhanced security controls for critical infrastructure. For agentic AI systems, this includes protecting critical agent systems.",
    relatedASI: [],
  },
  "PM-9": {
    title: "Risk Management Strategy",
    description: "Develops and implements a risk management strategy for the organization.",
    implementation: "Organizations develop risk management strategies that define risk assessment and mitigation procedures. For agentic AI systems, strategies should address agentic AI-specific risks.",
    relatedASI: [],
  },
  "PM-10": {
    title: "Authorization Process",
    description: "Establishes procedures for authorizing systems for operation.",
    implementation: "Organizations establish authorization procedures including assessment and approval. For agentic AI systems, authorization should include assessment of agent security controls.",
    relatedASI: [],
  },
  "PM-11": {
    title: "Mission & Business Process Definition",
    description: "Defines organizational mission and business processes to inform security planning.",
    implementation: "Organizations document mission and business processes to guide security planning. For agentic AI systems, this includes defining agent roles and responsibilities.",
    relatedASI: [],
  },
  "PM-12": {
    title: "Insider Threat Program",
    description: "Implements a program to detect and mitigate insider threats.",
    implementation: "Organizations implement insider threat programs including monitoring and investigation procedures. For agentic AI systems, this includes monitoring for compromised agents or rogue agents.",
    relatedASI: ["ASI10"],
  },
  "PM-13": {
    title: "Security Awareness & Training",
    description: "Implements security awareness and training programs for organizational personnel.",
    implementation: "Organizations conduct security awareness training for all personnel. For agentic AI systems, training should address agentic AI security risks and proper agent usage.",
    relatedASI: [],
  },
  "PM-14": {
    title: "Testing, Training & Monitoring",
    description: "Implements procedures for testing, training, and monitoring of security controls.",
    implementation: "Organizations establish procedures for regular testing, training, and monitoring of security controls. For agentic AI systems, this includes testing agent security controls and monitoring agent behavior.",
    relatedASI: [],
  },
  "PM-15": {
    title: "Contacts with Security Agencies & Organizations",
    description: "Maintains contacts with security agencies and organizations for information sharing.",
    implementation: "Organizations establish relationships with security agencies and information sharing organizations. For agentic AI systems, this includes participating in agentic AI security information sharing.",
    relatedASI: [],
  },
  "PM-16": {
    title: "Threat Awareness Program",
    description: "Implements a program to maintain awareness of current threats and vulnerabilities.",
    implementation: "Organizations maintain awareness of current threats and vulnerabilities through threat intelligence. For agentic AI systems, this includes monitoring for agentic AI-specific threats.",
    relatedASI: [],
  },

  // RA — Risk Assessment
  "RA-1": {
    title: "Risk Assessment Policy & Procedures",
    description: "Establishes and documents risk assessment policies and procedures.",
    implementation: "Organizations develop risk assessment policies that define assessment scope, frequency, and methodology. For agentic AI systems, policies must address assessment of agentic AI-specific risks.",
    relatedASI: [],
  },
  "RA-2": {
    title: "Risk Assessment",
    description: "Conducts risk assessments to identify threats, vulnerabilities, and risks to systems.",
    implementation: "Organizations perform periodic risk assessments using established methodologies. For agentic AI systems, assessments should evaluate agent-specific threats including goal hijack, tool misuse, and cascading failures.",
    relatedASI: [],
  },
  "RA-3": {
    title: "Risk Response",
    description: "Responds to identified risks through mitigation, acceptance, avoidance, or transfer.",
    implementation: "Organizations develop risk response strategies for identified risks. For agentic AI systems, responses should address agentic AI-specific risks through appropriate controls.",
    relatedASI: [],
  },
  "RA-5": {
    title: "Vulnerability Monitoring & Scanning",
    description: "Monitors systems for vulnerabilities and conducts vulnerability scans.",
    implementation: "Organizations implement vulnerability scanning and monitoring procedures. For agentic AI systems, this includes scanning for agent-specific vulnerabilities.",
    relatedASI: [],
  },
  "RA-6": {
    title: "Technical Surveillance Countermeasures",
    description: "Implements countermeasures against technical surveillance threats.",
    implementation: "Organizations implement technical surveillance countermeasures where appropriate. For agentic AI systems, this includes protecting against surveillance of agent communications.",
    relatedASI: [],
  },
  "RA-7": {
    title: "Risk Reassessment",
    description: "Reassesses risks periodically or when significant system changes occur.",
    implementation: "Organizations conduct periodic risk reassessments to maintain current risk knowledge. For agentic AI systems, reassessments should occur when agent capabilities or deployment changes.",
    relatedASI: [],
  },
  "RA-8": {
    title: "Threat Modeling",
    description: "Conducts threat modeling to identify potential threats and attack vectors.",
    implementation: "Organizations conduct threat modeling during system design and development. For agentic AI systems, threat modeling should address agentic AI-specific attack vectors.",
    relatedASI: [],
  },
  "RA-9": {
    title: "Criticality Analysis",
    description: "Analyzes system criticality to prioritize security controls and resources.",
    implementation: "Organizations analyze system criticality to identify critical functions and data. For agentic AI systems, this includes identifying critical agent functions and prioritizing their protection.",
    relatedASI: [],
  },

  // SA — System & Services Acquisition
  "SA-1": {
    title: "System & Services Acquisition Policy & Procedures",
    description: "Establishes and documents policies and procedures for acquiring systems and services.",
    implementation: "Organizations develop acquisition policies that define requirements, evaluation criteria, and security requirements. For agentic AI systems, policies must include security requirements for agent tools and services.",
    relatedASI: ["ASI04"],
  },
  "SA-2": {
    title: "Allocation of Resources",
    description: "Allocates resources for security during system and services acquisition.",
    implementation: "Organizations allocate adequate resources for security during acquisition. For agentic AI systems, this includes resources for security evaluation of agent tools and services.",
    relatedASI: [],
  },
  "SA-3": {
    title: "System Development Life Cycle",
    description: "Integrates security throughout the system development life cycle.",
    implementation: "Organizations implement secure development practices including security requirements, design review, and testing. For agentic AI systems, this includes security practices for agent development.",
    relatedASI: [],
  },
  "SA-4": {
    title: "Acquisition Process",
    description: "Includes security requirements in system and services acquisition processes.",
    implementation: "Organizations include security requirements in acquisition documents and contracts. For agentic AI systems, this includes security requirements for agent tools and services.",
    relatedASI: ["ASI04"],
  },
  "SA-5": {
    title: "Information System Documentation",
    description: "Obtains, reviews, and maintains system documentation.",
    implementation: "Organizations obtain and maintain system documentation including design, configuration, and security documentation. For agentic AI systems, this includes documentation of agent architecture and security controls.",
    relatedASI: [],
  },
  "SA-6": {
    title: "Software Usage Restrictions",
    description: "Restricts software use to authorized purposes and implements license compliance.",
    implementation: "Organizations implement software license compliance and usage restrictions. For agentic AI systems, this includes restricting agent tool usage to authorized purposes.",
    relatedASI: ["ASI02"],
  },
  "SA-7": {
    title: "User-Installed Software",
    description: "Restricts user installation of software and implements controls to prevent unauthorized installation.",
    implementation: "Organizations implement controls to prevent unauthorized software installation. For agentic AI systems, this includes preventing agents from installing unauthorized tools.",
    relatedASI: ["ASI02", "ASI05"],
  },
  "SA-8": {
    title: "Security & Privacy in System Life Cycle",
    description: "Integrates security and privacy throughout the system life cycle.",
    implementation: "Organizations implement security and privacy practices throughout system development. For agentic AI systems, this includes security and privacy practices for agent development.",
    relatedASI: [],
  },
  "SA-9": {
    title: "External Information System Services",
    description: "Establishes procedures for acquiring and managing external information system services.",
    implementation: "Organizations establish procedures for acquiring and managing external services including security requirements. For agentic AI systems, this includes acquiring external agent services with appropriate security controls.",
    relatedASI: ["ASI04"],
  },
  "SA-10": {
    title: "Developer Configuration Management",
    description: "Requires developers to implement configuration management during system development.",
    implementation: "Organizations require developers to implement configuration management practices. For agentic AI systems, this includes configuration management for agent development.",
    relatedASI: [],
  },
  "SA-11": {
    title: "Developer Security Testing & Evaluation",
    description: "Requires developers to conduct security testing and evaluation during development.",
    implementation: "Organizations require developers to conduct security testing including static analysis, dynamic testing, and penetration testing. For agentic AI systems, this includes security testing of agent components.",
    relatedASI: [],
  },
  "SA-12": {
    title: "Supply Chain Protection",
    description: "Implements controls to protect the supply chain from tampering and unauthorized modification.",
    implementation: "Organizations implement supply chain protection measures including verification of authenticity and integrity. For agentic AI systems, this includes verifying authenticity of agent tools and components.",
    relatedASI: ["ASI04"],
  },
  "SA-13": {
    title: "Trustworthiness",
    description: "Establishes requirements for system trustworthiness and implements controls to achieve trustworthiness.",
    implementation: "Organizations establish trustworthiness requirements and implement controls to achieve them. For agentic AI systems, this includes establishing agent trustworthiness requirements.",
    relatedASI: [],
  },
  "SA-14": {
    title: "Criticality Analysis",
    description: "Conducts criticality analysis during system development to identify critical functions.",
    implementation: "Organizations conduct criticality analysis to identify critical system functions. For agentic AI systems, this includes identifying critical agent functions.",
    relatedASI: [],
  },
  "SA-15": {
    title: "Development Process, Standards & Tools",
    description: "Requires developers to use approved development processes, standards, and tools.",
    implementation: "Organizations establish approved development processes, standards, and tools. For agentic AI systems, this includes approved processes and tools for agent development.",
    relatedASI: [],
  },
  "SA-16": {
    title: "Developer-Provided Training",
    description: "Requires developers to provide training on system security features.",
    implementation: "Organizations require developers to provide security training for system users. For agentic AI systems, this includes training on agent security features and limitations.",
    relatedASI: [],
  },
  "SA-17": {
    title: "Developer Security Architecture & Design",
    description: "Requires developers to implement security architecture and design practices.",
    implementation: "Organizations require developers to implement security architecture and design practices. For agentic AI systems, this includes security architecture for agent systems.",
    relatedASI: [],
  },
  "SA-18": {
    title: "Tamper Protection",
    description: "Implements tamper protection mechanisms to detect and prevent unauthorized modification.",
    implementation: "Organizations implement tamper protection mechanisms including physical seals and cryptographic hashing. For agentic AI systems, this includes tamper protection for agent configurations.",
    relatedASI: ["ASI04"],
  },
  "SA-19": {
    title: "Component Authenticity",
    description: "Verifies the authenticity of system components to prevent counterfeit components.",
    implementation: "Organizations implement procedures to verify component authenticity. For agentic AI systems, this includes verifying authenticity of agent tools and components.",
    relatedASI: ["ASI04"],
  },
  "SA-20": {
    title: "Customized Development of Critical Components",
    description: "Implements customized development practices for critical system components.",
    implementation: "Organizations implement customized development practices for critical components. For agentic AI systems, this includes customized development for critical agent components.",
    relatedASI: [],
  },
  "SA-21": {
    title: "Developer Screening",
    description: "Requires background screening and security clearances for developers with access to sensitive systems.",
    implementation: "Organizations conduct background screening and require security clearances for developers. For agentic AI systems, this includes screening for developers with access to agent systems.",
    relatedASI: [],
  },
  "SA-22": {
    title: "Unsupported System Components",
    description: "Restricts use of unsupported system components and implements compensating controls.",
    implementation: "Organizations restrict use of unsupported components and implement compensating controls. For agentic AI systems, this includes restricting use of unsupported agent tools.",
    relatedASI: [],
  },

  // SC — System & Communications Protection
  "SC-1": {
    title: "System & Communications Protection Policy & Procedures",
    description: "Establishes and documents system and communications protection policies and procedures.",
    implementation: "Organizations develop policies for protecting systems and communications. For agentic AI systems, policies must address protection of agent communications and data.",
    relatedASI: ["ASI07"],
  },
  "SC-2": {
    title: "Application Partitioning",
    description: "Partitions applications into separate execution domains to limit the impact of compromise.",
    implementation: "Organizations partition applications to isolate critical functions. For agentic AI systems, this includes isolating agent components to limit impact of compromise.",
    relatedASI: ["ASI08"],
  },
  "SC-3": {
    title: "Security Function Isolation",
    description: "Isolates security functions from non-security functions to prevent compromise.",
    implementation: "Organizations isolate security functions in separate components. For agentic AI systems, this includes isolating agent security monitoring from agent execution.",
    relatedASI: ["ASI08"],
  },
  "SC-4": {
    title: "Information in Shared Resources",
    description: "Prevents unauthorized information disclosure through shared system resources.",
    implementation: "Organizations implement controls to prevent information leakage through shared resources. For agentic AI systems, this includes preventing information leakage between agents sharing resources.",
    relatedASI: ["ASI06"],
  },
  "SC-5": {
    title: "Denial of Service Protection",
    description: "Implements controls to protect systems from denial of service attacks.",
    implementation: "Organizations implement DoS protection mechanisms including rate limiting and traffic filtering. For agentic AI systems, this includes protecting agent systems from DoS attacks.",
    relatedASI: [],
  },
  "SC-6": {
    title: "Resource Availability",
    description: "Protects the availability of system resources to prevent resource exhaustion.",
    implementation: "Organizations implement controls to ensure resource availability. For agentic AI systems, this includes ensuring agent system resource availability.",
    relatedASI: ["ASI08"],
  },
  "SC-7": {
    title: "Boundary Protection",
    description: "Monitors and controls communications at system boundaries to prevent unauthorized access.",
    implementation: "Organizations implement boundary protection mechanisms including firewalls and intrusion detection. For agentic AI systems, this includes monitoring agent communications at system boundaries.",
    relatedASI: ["ASI07"],
  },
  "SC-8": {
    title: "Transmission Confidentiality & Integrity",
    description: "Protects the confidentiality and integrity of information during transmission.",
    implementation: "Organizations implement encryption and integrity protection for transmitted data. For agentic AI systems, this includes encrypting agent communications and protecting against tampering.",
    relatedASI: ["ASI07"],
  },
  "SC-9": {
    title: "Transmission with Organization-Controlled Endpoints",
    description: "Restricts transmission of sensitive information to organization-controlled endpoints.",
    implementation: "Organizations restrict transmission of sensitive information to trusted endpoints. For agentic AI systems, this includes restricting agent communication to authorized systems.",
    relatedASI: ["ASI07"],
  },
  "SC-10": {
    title: "Network Disconnect",
    description: "Terminates network connections after a period of inactivity.",
    implementation: "Organizations implement automatic session termination after inactivity. For agentic AI systems, this includes terminating agent connections after inactivity.",
    relatedASI: [],
  },
  "SC-11": {
    title: "Trusted Path",
    description: "Establishes a trusted path for user communication with security functions.",
    implementation: "Organizations establish trusted paths for sensitive user interactions. For agentic AI systems, this includes establishing trusted paths for agent goal modification.",
    relatedASI: ["ASI01"],
  },
  "SC-12": {
    title: "Cryptographic Key Establishment & Management",
    description: "Manages cryptographic keys used for system protection.",
    implementation: "Organizations establish procedures for generating, storing, protecting, and retiring cryptographic keys. For agentic AI systems, this includes managing keys used for agent communications.",
    relatedASI: [],
  },
  "SC-13": {
    title: "Cryptographic Protection",
    description: "Implements cryptographic protection for information at rest and in transit.",
    implementation: "Organizations implement cryptographic protection using approved algorithms. For agentic AI systems, this includes encrypting agent data and communications.",
    relatedASI: ["ASI06", "ASI07"],
  },
  "SC-14": {
    title: "Public Access Protections",
    description: "Protects publicly accessible systems from unauthorized access.",
    implementation: "Organizations implement enhanced security controls for publicly accessible systems. For agentic AI systems, this includes protecting publicly accessible agent interfaces.",
    relatedASI: [],
  },
  "SC-15": {
    title: "Collaborative Computing Devices & Applications",
    description: "Protects collaborative computing devices from unauthorized access.",
    implementation: "Organizations implement security controls for collaborative computing devices. For agentic AI systems, this includes protecting collaborative agent systems.",
    relatedASI: [],
  },
  "SC-16": {
    title: "Transmission of Security Parameters",
    description: "Protects the transmission of security parameters between systems.",
    implementation: "Organizations protect transmission of security parameters using encryption. For agentic AI systems, this includes protecting transmission of agent security parameters.",
    relatedASI: [],
  },
  "SC-17": {
    title: "Public Key Infrastructure Certificates",
    description: "Implements public key infrastructure (PKI) for certificate management.",
    implementation: "Organizations implement PKI for certificate generation, distribution, and revocation. For agentic AI systems, this includes using PKI for agent authentication certificates.",
    relatedASI: [],
  },
  "SC-18": {
    title: "Mobile Code",
    description: "Restricts and controls mobile code (applets, scripts) to prevent unauthorized execution.",
    implementation: "Organizations restrict mobile code execution and implement controls to prevent malicious code. For agentic AI systems, this includes restricting agent-generated code execution.",
    relatedASI: ["ASI05"],
  },
  "SC-19": {
    title: "Voice Over Internet Protocol",
    description: "Implements security controls for voice over IP communications.",
    implementation: "Organizations implement security controls for VoIP systems. For agentic AI systems, this includes securing agent voice communications if applicable.",
    relatedASI: [],
  },
  "SC-20": {
    title: "Secure Name/Address Resolution Service (DNS & DNSSEC)",
    description: "Implements DNSSEC to protect DNS resolution from tampering.",
    implementation: "Organizations implement DNSSEC to protect DNS resolution. For agentic AI systems, this includes using DNSSEC for agent service discovery.",
    relatedASI: [],
  },
  "SC-21": {
    title: "Secure Name/Address Resolution Service (DNS) – Data Origin Authentication",
    description: "Implements data origin authentication for DNS responses.",
    implementation: "Organizations implement DNS security mechanisms to verify response authenticity. For agentic AI systems, this includes verifying DNS responses for agent service discovery.",
    relatedASI: [],
  },
  "SC-22": {
    title: "Architecture & Provisioning for Name/Address Resolution Service",
    description: "Implements redundancy and failover for DNS services.",
    implementation: "Organizations implement redundant DNS services with failover. For agentic AI systems, this includes redundant DNS for agent service discovery.",
    relatedASI: [],
  },
  "SC-23": {
    title: "Session Authenticity",
    description: "Protects the authenticity of sessions to prevent session hijacking.",
    implementation: "Organizations implement session protection mechanisms including cryptographic tokens. For agentic AI systems, this includes protecting agent session authenticity.",
    relatedASI: ["ASI03"],
  },
  "SC-24": {
    title: "Fail in Secure State",
    description: "Ensures systems fail in a secure state to prevent unauthorized access.",
    implementation: "Organizations implement fail-safe mechanisms to ensure secure failure. For agentic AI systems, this includes ensuring agents fail safely without exposing sensitive data.",
    relatedASI: ["ASI08"],
  },
  "SC-25": {
    title: "Thin Nodes",
    description: "Implements security controls for thin client systems.",
    implementation: "Organizations implement security controls for thin client deployments. For agentic AI systems, this includes securing thin client access to agent systems.",
    relatedASI: [],
  },
  "SC-26": {
    title: "Decoupled or Physically Separated Information System Components",
    description: "Decouples or physically separates system components to limit impact of compromise.",
    implementation: "Organizations decouple system components to prevent cascading failures. For agentic AI systems, this includes decoupling agent components to prevent cascading failures.",
    relatedASI: ["ASI08"],
  },
  "SC-27": {
    title: "Platform-Independent Applications",
    description: "Implements platform-independent applications to reduce security dependencies.",
    implementation: "Organizations use platform-independent technologies where appropriate. For agentic AI systems, this includes using platform-independent agent frameworks.",
    relatedASI: [],
  },
  "SC-28": {
    title: "Protection of Information at Rest",
    description: "Protects information at rest through encryption and other mechanisms.",
    implementation: "Organizations implement encryption and access controls for data at rest. For agentic AI systems, this includes encrypting agent data and configurations at rest.",
    relatedASI: ["ASI06"],
  },
  "SC-29": {
    title: "Heterogeneous Redundancy",
    description: "Implements heterogeneous redundancy using different technologies to prevent common failures.",
    implementation: "Organizations implement redundancy using different technologies. For agentic AI systems, this includes using heterogeneous agent deployment to prevent common failures.",
    relatedASI: ["ASI08"],
  },
  "SC-30": {
    title: "Access Points",
    description: "Limits and monitors access points to systems.",
    implementation: "Organizations limit and monitor system access points. For agentic AI systems, this includes limiting agent access points.",
    relatedASI: [],
  },
  "SC-31": {
    title: "Covert Channels",
    description: "Analyzes systems for covert channels and implements controls to limit covert channel bandwidth.",
    implementation: "Organizations analyze systems for covert channels and implement controls. For agentic AI systems, this includes analyzing for covert channels in agent communications.",
    relatedASI: [],
  },
  "SC-32": {
    title: "Information System Monitoring",
    description: "Monitors information systems for security events and anomalies.",
    implementation: "Organizations implement monitoring systems to detect security events. For agentic AI systems, this includes monitoring agent behavior for anomalies.",
    relatedASI: ["ASI01", "ASI08"],
  },
  "SC-33": {
    title: "Transmission Preparation Integrity",
    description: "Protects the integrity of information during preparation for transmission.",
    implementation: "Organizations implement integrity protection for data preparation. For agentic AI systems, this includes protecting agent data integrity during preparation.",
    relatedASI: [],
  },
  "SC-34": {
    title: "Non-Modifiability of Information",
    description: "Implements controls to prevent modification of information.",
    implementation: "Organizations implement write-once storage and other controls to prevent modification. For agentic AI systems, this includes protecting agent configurations from modification.",
    relatedASI: ["ASI01"],
  },
  "SC-35": {
    title: "Honeypots, Honeynets & Deception",
    description: "Implements honeypots and deception mechanisms to detect attacks.",
    implementation: "Organizations implement honeypots and deception mechanisms. For agentic AI systems, this includes implementing deception to detect agent compromise.",
    relatedASI: ["ASI10"],
  },
  "SC-36": {
    title: "Distributed Processing & Storage",
    description: "Distributes processing and storage across multiple systems to prevent single point of failure.",
    implementation: "Organizations distribute processing and storage to improve resilience. For agentic AI systems, this includes distributing agent processing to prevent cascading failures.",
    relatedASI: ["ASI08"],
  },
  "SC-37": {
    title: "Out-of-Band Channels",
    description: "Implements out-of-band channels for critical communications.",
    implementation: "Organizations implement out-of-band communication channels for critical functions. For agentic AI systems, this includes out-of-band channels for agent shutdown commands.",
    relatedASI: ["ASI08"],
  },
  "SC-38": {
    title: "Operations Security",
    description: "Implements operations security (OPSEC) procedures to protect sensitive information.",
    implementation: "Organizations implement OPSEC procedures to prevent information disclosure. For agentic AI systems, this includes OPSEC for agent operations.",
    relatedASI: ["ASI06"],
  },
  "SC-39": {
    title: "Process Isolation",
    description: "Isolates processes to prevent interference between processes.",
    implementation: "Organizations implement process isolation mechanisms. For agentic AI systems, this includes isolating agent processes to prevent interference.",
    relatedASI: ["ASI08"],
  },
  "SC-40": {
    title: "Wireless Access",
    description: "Implements security controls for wireless access.",
    implementation: "Organizations implement security controls for wireless networks. For agentic AI systems, this includes securing wireless access to agent systems.",
    relatedASI: [],
  },
  "SC-41": {
    title: "Port & I/O Device Access",
    description: "Restricts access to system ports and I/O devices.",
    implementation: "Organizations restrict access to system ports and I/O devices. For agentic AI systems, this includes restricting agent access to system ports.",
    relatedASI: [],
  },
  "SC-42": {
    title: "Sensor Capability & Activation",
    description: "Controls sensor activation and restricts sensor data collection.",
    implementation: "Organizations control sensor activation and restrict data collection. For agentic AI systems, this includes controlling agent sensor access.",
    relatedASI: [],
  },
  "SC-43": {
    title: "Usage Restrictions",
    description: "Restricts use of system functions to authorized purposes.",
    implementation: "Organizations restrict system function usage to authorized purposes. For agentic AI systems, this includes restricting agent tool usage to authorized purposes.",
    relatedASI: ["ASI02"],
  },
  "SC-44": {
    title: "Deactivation of Wireless Networking",
    description: "Provides capability to deactivate wireless networking.",
    implementation: "Organizations implement wireless deactivation capabilities. For agentic AI systems, this includes deactivating agent wireless capabilities if needed.",
    relatedASI: [],
  },
  "SC-45": {
    title: "Session Establishment",
    description: "Establishes sessions in a secure manner.",
    implementation: "Organizations implement secure session establishment procedures. For agentic AI systems, this includes secure agent session establishment.",
    relatedASI: ["ASI03"],
  },
  "SC-46": {
    title: "Crossdomain & Intra-Domain Handshakes",
    description: "Implements secure handshakes for cross-domain and intra-domain communications.",
    implementation: "Organizations implement secure handshake procedures. For agentic AI systems, this includes secure handshakes for agent-to-system communications.",
    relatedASI: ["ASI07"],
  },
  "SC-47": {
    title: "Host-Based Advanced Malware Protection",
    description: "Implements advanced malware protection on host systems.",
    implementation: "Organizations implement host-based malware detection and prevention. For agentic AI systems, this includes malware protection for agent execution environments.",
    relatedASI: ["ASI05"],
  },
  "SC-48": {
    title: "Wireless Intrusion Detection",
    description: "Implements wireless intrusion detection systems.",
    implementation: "Organizations implement wireless intrusion detection. For agentic AI systems, this includes detecting unauthorized wireless access to agent systems.",
    relatedASI: [],
  },

  // SI — System & Information Integrity
  "SI-1": {
    title: "System & Information Integrity Policy & Procedures",
    description: "Establishes and documents system and information integrity policies and procedures.",
    implementation: "Organizations develop policies for maintaining system and information integrity. For agentic AI systems, policies must address maintaining agent integrity and preventing tampering.",
    relatedASI: ["ASI01"],
  },
  "SI-2": {
    title: "Flaw Remediation",
    description: "Identifies and remediates software flaws and vulnerabilities.",
    implementation: "Organizations establish procedures for identifying, testing, and deploying security patches. For agentic AI systems, this includes patching agent components and dependencies.",
    relatedASI: [],
  },
  "SI-3": {
    title: "Malicious Code Protection",
    description: "Implements malicious code detection and prevention mechanisms.",
    implementation: "Organizations implement antivirus and anti-malware tools. For agentic AI systems, this includes protecting agent systems from malicious code.",
    relatedASI: ["ASI01", "ASI05"],
  },
  "SI-4": {
    title: "Information System Monitoring",
    description: "Monitors information systems for security events and anomalies.",
    implementation: "Organizations implement system monitoring and logging. For agentic AI systems, this includes monitoring agent behavior for anomalies.",
    relatedASI: ["ASI01", "ASI08"],
  },
  "SI-5": {
    title: "Security Alerts & Advisories",
    description: "Receives and processes security alerts and advisories.",
    implementation: "Organizations subscribe to security alert services and process advisories. For agentic AI systems, this includes monitoring for agent-related security advisories.",
    relatedASI: ["ASI01"],
  },
  "SI-6": {
    title: "Security Functionality Verification",
    description: "Verifies the correct operation of security functions.",
    implementation: "Organizations implement security function verification procedures. For agentic AI systems, this includes verifying agent security controls are functioning correctly.",
    relatedASI: ["ASI01"],
  },
  "SI-7": {
    title: "Software, Firmware & Information Integrity",
    description: "Monitors and verifies the integrity of software, firmware, and information.",
    implementation: "Organizations implement integrity checking using cryptographic hashing or digital signatures. For agentic AI systems, this includes verifying agent code and configuration integrity.",
    relatedASI: ["ASI01"],
  },
  "SI-8": {
    title: "Spam & Phishing Protection",
    description: "Implements spam and phishing detection and prevention.",
    implementation: "Organizations implement email filtering and anti-phishing tools. For agentic AI systems, this includes protecting agents from phishing attacks.",
    relatedASI: ["ASI01"],
  },
  "SI-9": {
    title: "Information System Monitoring Tools & Techniques",
    description: "Implements monitoring tools and techniques to detect security events.",
    implementation: "Organizations implement monitoring tools including SIEM and IDS/IPS. For agentic AI systems, this includes tools for monitoring agent behavior.",
    relatedASI: ["ASI01", "ASI08"],
  },
  "SI-10": {
    title: "Information Input Validation",
    description: "Validates information inputs to prevent injection attacks and malformed data.",
    implementation: "Organizations implement input validation procedures. For agentic AI systems, this includes validating inputs to agents to prevent prompt injection and other attacks.",
    relatedASI: ["ASI01", "ASI02"],
  },
  "SI-11": {
    title: "Error Handling",
    description: "Implements error handling procedures that prevent information disclosure.",
    implementation: "Organizations implement error handling that prevents sensitive information disclosure. For agentic AI systems, this includes error handling in agent responses.",
    relatedASI: ["ASI06"],
  },
  "SI-12": {
    title: "Information Handling & Retention",
    description: "Handles and retains information according to organizational policies.",
    implementation: "Organizations establish information handling and retention policies. For agentic AI systems, this includes handling and retention of agent interaction logs.",
    relatedASI: [],
  },
  "SI-13": {
    title: "Predictable Failure Prevention",
    description: "Implements controls to prevent predictable failures.",
    implementation: "Organizations implement controls to prevent common failure modes. For agentic AI systems, this includes preventing predictable agent failures.",
    relatedASI: ["ASI08"],
  },
  "SI-14": {
    title: "Non-Persistence",
    description: "Implements non-persistent computing environments that reset to a known state.",
    implementation: "Organizations implement non-persistent systems that reset after each use. For agentic AI systems, this includes non-persistent agent execution environments.",
    relatedASI: ["ASI05"],
  },
  "SI-15": {
    title: "Information Output Filtering",
    description: "Filters information output to prevent unauthorized disclosure.",
    implementation: "Organizations implement output filtering to prevent sensitive information disclosure. For agentic AI systems, this includes filtering agent output to prevent information leakage.",
    relatedASI: ["ASI06"],
  },
  "SI-16": {
    title: "Memory Protection",
    description: "Implements memory protection mechanisms to prevent unauthorized access.",
    implementation: "Organizations implement memory protection including ASLR and DEP. For agentic AI systems, this includes memory protection for agent processes.",
    relatedASI: ["ASI05"],
  },
  "SI-17": {
    title: "Fail-Safe Procedures",
    description: "Implements fail-safe procedures to ensure systems fail securely.",
    implementation: "Organizations implement fail-safe mechanisms. For agentic AI systems, this includes fail-safe procedures for agent shutdown.",
    relatedASI: ["ASI08"],
  },
  "SI-18": {
    title: "Personally Identifiable Information (PII) Processing Restrictions",
    description: "Restricts processing of personally identifiable information.",
    implementation: "Organizations restrict PII processing to authorized purposes. For agentic AI systems, this includes restricting agent access to PII.",
    relatedASI: ["ASI06"],
  },
  "SI-19": {
    title: "Development, Test & Operational Environments",
    description: "Maintains separate development, test, and operational environments.",
    implementation: "Organizations maintain separate environments with appropriate controls. For agentic AI systems, this includes separate agent development, test, and production environments.",
    relatedASI: [],
  },
  "SI-20": {
    title: "Tainting & Tracking",
    description: "Implements tainting and tracking of information to detect unauthorized disclosure.",
    implementation: "Organizations implement data tainting and tracking mechanisms. For agentic AI systems, this includes tracking agent data to detect unauthorized disclosure.",
    relatedASI: ["ASI06"],
  },
  "SI-21": {
    title: "Information Refresh",
    description: "Refreshes information to prevent accumulation of sensitive data.",
    implementation: "Organizations implement information refresh procedures. For agentic AI systems, this includes refreshing agent memory to prevent accumulation of sensitive data.",
    relatedASI: ["ASI06"],
  },
  "SI-22": {
    title: "Information Accuracy, Completeness, Validity & Authenticity",
    description: "Ensures information accuracy, completeness, validity, and authenticity.",
    implementation: "Organizations implement controls to ensure information quality. For agentic AI systems, this includes ensuring accuracy of agent training data and responses.",
    relatedASI: [],
  },

  // SR — Supply Chain Risk Management
  "SR-1": {
    title: "Supply Chain Risk Management Policy & Procedures",
    description: "Establishes and documents supply chain risk management policies and procedures.",
    implementation: "Organizations develop supply chain risk policies that address vendor management and risk assessment. For agentic AI systems, policies must address supply chain risks for agent tools and components.",
    relatedASI: ["ASI04"],
  },
  "SR-2": {
    title: "Supply Chain Risk Management Plan",
    description: "Develops and maintains a supply chain risk management plan.",
    implementation: "Organizations develop supply chain risk plans that identify critical suppliers and risks. For agentic AI systems, plans should address risks from agent tool suppliers.",
    relatedASI: ["ASI04"],
  },
  "SR-3": {
    title: "Supply Chain Controls & Processes",
    description: "Implements controls and processes to manage supply chain risks.",
    implementation: "Organizations implement controls for supplier management including audits and assessments. For agentic AI systems, this includes assessing security of agent tool suppliers.",
    relatedASI: ["ASI04"],
  },
  "SR-4": {
    title: "Supplier Agreements",
    description: "Includes security requirements in supplier agreements.",
    implementation: "Organizations include security requirements in contracts with suppliers. For agentic AI systems, this includes security requirements for agent tool suppliers.",
    relatedASI: ["ASI04"],
  },
  "SR-5": {
    title: "Acquisition Processes & Criteria",
    description: "Implements acquisition processes that include supply chain risk assessment.",
    implementation: "Organizations implement acquisition processes that assess supply chain risks. For agentic AI systems, this includes assessing supply chain risks during agent tool acquisition.",
    relatedASI: ["ASI04"],
  },
  "SR-6": {
    title: "Supplier Assessments & Audits",
    description: "Conducts assessments and audits of suppliers.",
    implementation: "Organizations conduct periodic supplier assessments and audits. For agentic AI systems, this includes auditing agent tool suppliers.",
    relatedASI: ["ASI04"],
  },
  "SR-7": {
    title: "Supplier Continuous Monitoring",
    description: "Monitors suppliers continuously to ensure ongoing compliance.",
    implementation: "Organizations implement continuous monitoring of suppliers. For agentic AI systems, this includes monitoring agent tool suppliers for security issues.",
    relatedASI: ["ASI04"],
  },
  "SR-8": {
    title: "Notification & Incident Response",
    description: "Establishes procedures for supplier notification and incident response.",
    implementation: "Organizations establish procedures for notifying suppliers of security incidents. For agentic AI systems, this includes notifying agent tool suppliers of security issues.",
    relatedASI: ["ASI04"],
  },
  "SR-9": {
    title: "Supplier Security Incident Response",
    description: "Implements procedures for responding to supplier security incidents.",
    implementation: "Organizations implement procedures for responding to supplier security incidents. For agentic AI systems, this includes responding to security incidents from agent tool suppliers.",
    relatedASI: ["ASI04"],
  },
  "SR-10": {
    title: "Supplier Sanctions",
    description: "Implements sanctions for suppliers that violate security requirements.",
    implementation: "Organizations implement sanctions for non-compliant suppliers. For agentic AI systems, this includes sanctions for agent tool suppliers that violate security requirements.",
    relatedASI: ["ASI04"],
  },
  "SR-11": {
    title: "Supplier Information Security Agreements",
    description: "Establishes information security agreements with suppliers.",
    implementation: "Organizations establish security agreements with suppliers. For agentic AI systems, this includes security agreements with agent tool suppliers.",
    relatedASI: ["ASI04"],
  },
  "SR-12": {
    title: "Supply Chain Risk Management Program",
    description: "Implements a comprehensive supply chain risk management program.",
    implementation: "Organizations implement comprehensive supply chain risk programs. For agentic AI systems, this includes programs for managing agent tool supply chain risks.",
    relatedASI: ["ASI04"],
  },
};
