/**
 * @file scrambler-evaluator.ts
 * @description Evaluates a generated FactPattern to produce a complete ScenarioResult.
 * Determines Active/Broken/Irrelevant cell states for the Scrambler heatmap.
 */

import {
  CROSSWALK,
  OWASP_ASI,
} from './data';
import {
  FAMILY_TO_PRIMARY_BOOLEAN,
  RISK_TO_ASI,
} from './scrambler-mappings';
import type {
  CellState,
  ControlEvaluation,
  FactPattern,
  ScenarioResult,
} from './scrambler-types';

/**
 * Determines the state of a single cell in the Scrambler heatmap.
 *
 * @param asiId The OWASP ASI risk ID (e.g., "ASI01").
 * @param familyId The NIST 800-53 family ID (e.g., "AC").
 * @param controlState The current state of the 7 primary security booleans.
 * @param riskCategory The IMDA risk category for the scenario.
 * @returns The calculated state of the cell: "active", "broken", or "irrelevant".
 */
export function getCellState(
  asiId: string,
  familyId: string,
  controlState: Record<string, boolean>,
  riskCategory: string
): CellState {
  const relevantRisks = RISK_TO_ASI[riskCategory] || [];
  const isRiskRelevant = relevantRisks.some((r) => r.asiId === asiId);

  if (!isRiskRelevant) {
    return 'irrelevant';
  }

  const crosswalkEntry = CROSSWALK[asiId];
  const isFamilyInCrosswalk = crosswalkEntry?.nist53.some(
    (m) => m.family === familyId
  );

  if (!isFamilyInCrosswalk) {
    return 'irrelevant';
  }

  const governingBoolean = FAMILY_TO_PRIMARY_BOOLEAN[familyId];
  if (governingBoolean && controlState[governingBoolean] === false) {
    return 'broken';
  }

  return 'active';
}

/**
 * Generates a textual representation of the cascade path for multi-agent archetypes.
 *
 * @param archetype The agent archetype (e.g., "Sequential", "Supervisor", "Swarm").
 * @returns An array of strings representing the communication paths.
 */
function generateCascadePath(archetype: string): string[] {
  switch (archetype) {
    case 'Sequential':
      return ['Agent A → Agent B → Agent C'];
    case 'Supervisor':
      return [
        'Supervisor → Agent A',
        'Supervisor → Agent B',
        'Supervisor → Agent C',
      ];
    case 'Swarm':
      return [
        'Coordinator → Agent A',
        'Coordinator → Agent B',
        'Coordinator → Agent C',
        'Agent A ↔ Agent B',
        'Agent A ↔ Agent C',
        'Agent B ↔ Agent C',
      ];
    default:
      return [];
  }
}

/**
 * Evaluates a generated FactPattern to produce a complete ScenarioResult.
 *
 * @param fp The FactPattern generated by the scrambler.
 * @returns A full ScenarioResult including control evaluations and cascade paths.
 */
export function evaluateScenario(fp: FactPattern): ScenarioResult {
  const controls_evaluated: ControlEvaluation[] = [];
  const _implicatedAsiRisks = RISK_TO_ASI[fp.risk_category] || [];

  for (const asiRisk of OWASP_ASI) {
    const crosswalkEntry = CROSSWALK[asiRisk.id];
    if (!crosswalkEntry) continue;

    for (const nistMapping of crosswalkEntry.nist53) {
      const state = getCellState(
        asiRisk.id,
        nistMapping.family,
        fp.control_state,
        fp.risk_category
      );

      for (const control of nistMapping.controls) {
        controls_evaluated.push({
          control_id: control.split(' ')[0],
          family: nistMapping.family,
          state,
          rationale: nistMapping.rationale,
          mitigation: `Implementing ${control} helps mitigate risks associated with ${asiRisk.name}.`,
        });
      }
    }
  }

  const failure_injected = controls_evaluated.some(
    (c) => c.state === 'broken'
  );
  const cascade_path = generateCascadePath(fp.agent_archetype);

  let outcome = 'All controls effective. System remains secure.';
  if (failure_injected) {
    const brokenFamilies = Array.from(
      new Set(
        controls_evaluated
          .filter((c) => c.state === 'broken')
          .map((c) => c.family)
      )
    );
    outcome = `Security gaps detected in the following NIST families: ${brokenFamilies.join(', ')}. These gaps could lead to ${fp.risk_category.toLowerCase()} incidents.`;
  }

  return {
    failure_injected,
    controls_evaluated,
    outcome,
    checkpoint_results: [],
    cascade_path,
  };
}
