
/**
 * @file Defines the core data structures and types for the Agentic AI Security Scrambler.
 * These types are used for generating scenarios, evaluating them, and rendering the results.
 */

// ─── Core Scenario & Result Types ───────────────────────────────────────────

/**
 * Represents the complete input state for a single Scrambler scenario.
 * This is the primary data structure generated by the `scrambler-generator`.
 */
export interface FactPattern {
  /** The high-level IMDA risk category being simulated. */
  risk_category: 'Erroneous' | 'Unauthorised' | 'Biased' | 'DataBreach' | 'Disruption';

  /** The multi-agent architectural pattern being simulated. */
  agent_archetype: 'Single' | 'Sequential' | 'Supervisor' | 'Swarm';

  /** The set of seven security controls and their current state (present/absent). */
  control_state: {
    has_agent_limits: boolean;
    has_identity_management: boolean;
    has_oversight_design: boolean;
    has_dev_controls: boolean;
    has_testing: boolean;
    has_phased_deployment: boolean;
    has_monitoring: boolean;
  };

  /** Defines the potential negative consequences of a failure in this scenario. */
  impact_profile: {
    /** The tolerance for errors in the agent's operational domain (e.g., healthcare vs. content generation). */
    domain_error_tolerance: 'Low' | 'Medium' | 'High';
    /** The sensitivity of the data the agent has access to. */
    data_sensitivity: 'PII' | 'Confidential' | 'TradeSecret' | 'Public';
    /** The agent's level of access to external systems. */
    external_access: 'Sandboxed' | 'Internal' | 'External';
    /** The agent's ability to perform read-only vs. read-write actions. */
    action_scope: 'ReadOnly' | 'ReadWrite';
    /** The degree to which the agent's actions can be undone. */
    reversibility: 'Reversible' | 'Irreversible';
  };

  /** Defines the factors contributing to the likelihood of a failure. */
  likelihood_profile: {
    /** The degree of autonomous decision-making the agent possesses. */
    autonomy: 'Low' | 'Medium' | 'High';
    /** The complexity of the tasks the agent is designed to perform. */
    task_complexity: 'Simple' | 'Complex' | 'VeryComplex';
    /** The level of exposure the agent has to external inputs or actors. */
    external_exposure: 'None' | 'Minimal' | 'High';
  };
}

/**
 * Represents the evaluated outcome of a Scrambler scenario.
 * This is the primary data structure returned by the `scrambler-evaluator`.
 */
export interface ScenarioResult {
  /** A flag indicating if a specific failure was injected into the scenario. */
  failure_injected: boolean;

  /** An array detailing the state of each evaluated security control. */
  controls_evaluated: ControlEvaluation[];

  /** A summary of the overall scenario outcome. */
  outcome: string;

  /** An array of results from specific checkpoints in the evaluation. */
  checkpoint_results: CheckpointResult[];

  /** The path of failure propagation in a multi-agent scenario. */
  cascade_path: string[];
}

// ─── Supporting Interfaces & Types ──────────────────────────────────────────

/**
 * The state of a single cell in the Scrambler's heatmap grid.
 * - `active`: The control is present and effective for the given ASI risk.
 * - `broken`: The control is absent, and the ASI risk implicates the corresponding NIST family.
 * - `irrelevant`: The ASI risk does not implicate the NIST family, so the control's state is not a factor.
 */
export type CellState = 'active' | 'broken' | 'irrelevant';

/**
 * Details the evaluation of a single security control within a scenario.
 */
export interface ControlEvaluation {
  /** The ID of the control being evaluated (e.g., 'has_agent_limits'). */
  control_id: string;

  /** The NIST 800-53 family associated with this control. */
  family: string;

  /** The evaluated state of the control for the current scenario. */
  state: CellState;

  /** The reasoning behind the evaluated state. */
  rationale: string;

  /** Suggested mitigation actions if the control is 'broken'. */
  mitigation: string;
}

/**
 * Represents the result of a specific check performed during scenario evaluation.
 */
export interface CheckpointResult {
  /** The ID of the checkpoint. */
  checkpoint_id: string;

  /** A description of what was checked. */
  description: string;

  /** The outcome of the check (e.g., 'passed', 'failed'). */
  result: string;

  /** Additional details or data related to the check. */
  details: Record<string, any>;
}

/**
 * Defines the relevance of a specific OWASP ASI risk to an IMDA risk category.
 * Used in the `RISK_TO_ASI` mapping.
 */
export interface ASIRelevance {
  /** The ID of the OWASP ASI risk (e.g., 'ASI01'). */
  asiId: string;

  /** A weight (0.0-1.0) indicating the relevance of the ASI risk to the category. */
  weight: number;

  /** The rationale for the assigned weight and mapping. */
  rationale: string;

  /** A reference to the relevant section in the IMDA documentation. */
  imdaRef: string;
}

/**
 * Defines a rule for constraining the random generation of `FactPattern`s.
 * Predicate function returns `true` if the pattern is invalid.
 */
export interface ConstraintRule {
  /** A unique identifier for the rule (e.g., 'CR-01'). */
  id: string;

  /** A human-readable description of the constraint. */
  description: string;

  /** The predicate function that tests the `FactPattern`. Returns `true` if the constraint is violated. */
  predicate: (fp: FactPattern) => boolean;

  /** The source or justification for the rule (e.g., 'Logical contradiction', 'Pedagogical requirement'). */
  source: string;
}

/**
 * Represents the level of governance and security maturity applied to the agentic AI system.
 * Used in Guided Mode to generate scenarios with a predefined number of broken controls.
 */
export type GovernancePosture = 'Minimal' | 'Standard' | 'Full';

/**
 * A placeholder type for representing the potential blast radius of a failure.
 * This will be more fully defined in a future phase.
 */
export type BlastRadius = 'Contained' | 'Significant' | 'Catastrophic';
